%  mdload  Load data generated by molecular dynamics simulations.
%
%   MD = mdload(TopFile, TrajFile);
%
%   Input:
%     TrajFile       character array
%                    Name of trajectory output file.
%
%     TopFile        character array
%                    Name of topology input file used for molecular 
%                    dynamics simulations.
%
%     ResName        character array
%                    Name of residue assigned to spin label side chain,
%                    e.g. "CYR1" is the default used by CHARMM-GUI.
%
%     AtomNames      structure array
%                    Structure array containing the atom names used in the 
%                    PSF to refer to the following atoms in the nitroxide 
%                    molecule:
%
%                                   O (OName)
%                                   |
%                                   N (NName)
%                                  / \
%                        (C1Name) C   C (C2Name)
%                                 |   |
%                                ... ...
%
%
%   Output:
%     MD             structure array
%                    Oxyz
%                    Nxyz
%                    C1xyz
%                    C2xyz
%                    nSteps
%                    dt
%
%   Supported formats are identified via the extension
%   in 'TrajFile' and 'TopFile'. Extensions:
%
%     NAMD, CHARMM:        .DCD, .PSF
%

function MD = mdload(TrajFile, TopFile, ResName, AtomNames)

if ~ischar(TrajFile)||regexp(TrajFile,'\w+\.\w+','once')<1
  error('TrajFile must be given as a character array, including the filename extension.')
end

if numel(regexp(TrajFile,'\.'))>1
  error('Only one period (".") can be included in TrajFile as part of the filename extension. Remove the others.')
end

if ~ischar(TopFile)||regexp(TopFile,'\w+\.\w+','once')<1
  error('TopFile must be given as a character array, including the filename extension.')
end

if numel(regexp(TopFile,'\.'))>1
  error('Only one period (".") can be included in TopFile as part of the filename extension. Remove the others.')
end

[TrajFilePath, TrajFileName, TrajFileExt] = fileparts(TrajFile);
TrajFile = fullfile(TrajFilePath, [TrajFileName, TrajFileExt]);

[TopFilePath, TopFileName, TopFileExt] = fileparts(TopFile);
TopFile = fullfile(TopFilePath, [TopFileName, TopFileExt]);

switch upper(TrajFileExt)
  case '.DCD'
    if ~strcmp(upper(TopFileExt),'.PSF')
      error('If loading a DCD trajectory file, the topology file must be of type PSF.')
    end
    psf = readpsf(TopFile, ResName, AtomNames);
    MD = readdcd(TrajFile, psf.idx_SpinLabel);
    MD.Oxyz = MD.xyz(:,:,psf.idx_O==psf.idx_SpinLabel);
    MD.Nxyz = MD.xyz(:,:,psf.idx_N==psf.idx_SpinLabel);
    MD.C1xyz = MD.xyz(:,:,psf.idx_C1==psf.idx_SpinLabel);
    MD.C2xyz = MD.xyz(:,:,psf.idx_C2==psf.idx_SpinLabel);
    rmfield(MD, 'xyz');
  otherwise
    error('TrajFile type is either not supported or not properly entered. Please see documentation.')
end

end