function ok = test()

% Syntax check

SymmGroup = {'D2h','C2h','Ci','Dinfh'};
GridSize = 10;
for g = 1:numel(SymmGroup)
  [grid,tri] = sphgrid(SymmGroup{g},GridSize);
  ok(g) = isfield(grid,'phi') && ...
          isfield(grid,'theta') && ...
          isfield(grid,'vecs') && ...
          isfield(grid,'weights') && ...
          isfield(tri,'idx') && ...
          isfield(tri,'areas');
end
