function no = elementsymbol2no(symbol)

if numel(symbol)==1, symbol(2) = ' '; end

if numel(symbol)>2, symbol  = symbol(1:2); end

ElementSymbols = [...
  'H He'...
  'LiBeB C N O F Ne'...
  'NaMgAlSiP S ClAr'...
  'K CaScTiV CrMnFeCoNiCuZnGaGeAsSeBrKr'...
  'RbSrY ZrNbMoTcRuRhPdAgCdInSnSbTeI Xe'...
  'CsBaLaCePrNdPmSmEuGdTbDyHoerTmYbLuHfTaW ReOsIrPtAuHgTlPbBiPoAtRn'...
  'FrRaAcThPaU NpPuAmCmBkCfEsFmMdNoLrRfDbSgBhHsMtDsRgCn'];

idx = strfind(ElementSymbols,symbol);
no = (idx+1)/2;
